### ISSUE TITLE
Missing secret definition

### ISSUE THREAD

**Issue by BurnZeZ** [ReeseWang/eve-market-tools#1]
% python3 esiauth.py
Traceback (most recent call last):
  File "esiauth.py", line 5, in <module>
    import secret
ModuleNotFoundError: No module named 'secret'

Where exactly is this defined?

**Comment by ReeseWang** [comment]
Oops it's actually a project I started a week ago, no attention paid to user-friendliness, sorry.
There's a `secret.py` in my project folder which contains developer keys, etc and I definitely don't want to share with others and make it ignored by git.
Will soon add the details about this file in README.
